// AUTH ACTION TYPES
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const HANDLE_EMAIL = 'HANDLE_EMAIL';
export const HANDLE_PASSWORD = 'HANDLE_PASSWORD';
export const HANDLE_FIRSTNAME = 'HANDLE_FIRSTNAME';
export const HANDLE_LASTNAME = 'HANDLE_LASTNAME';
export const HANDLE_FORM = 'HANDLE_FORM';
export const RESET_AUTH = 'RESET_AUTH';

// MODAL ACTION TYPES
export const TOGGLE_USER_PANEL = 'TOGGLE_USER_PANEL';
export const SHOW_SETTINGS_BOX = 'SHOW_SETTINGS_BOX';
export const HIDE_SETTINGS_BOX = 'HIDE_SETTINGS_BOX';

// TRANSACTION ACTION TYPES
export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS';
export const SET_USER_TRANSACTIONS = 'SET_USER_TRANSACTIONS';
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

// ACCOUNT ACTION TYPES
export const GET_USER_ACCOUNTS = 'GET_USER_ACCOUNTS';
export const SET_USER_ACCOUNTS = 'SET_USER_ACCOUNTS';
export const GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// ACTION ACTION TYPES
export const GET_USER_ACTIONS = 'GET_USER_ACTIONS';

// PROFILE ACTION TYPES
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
